import { expect, test, type Page } from '@playwright/test'

test('客户注册与地址新增编辑删除，空经纬度保持合法', async ({ page }) => {
  await page.goto('/customer/register')
  await page.getByLabel('用户名', { exact: true }).fill('new_customer')
  await page.getByLabel('密码', { exact: true }).fill('NewPassword1')
  await page.getByLabel('称呼').fill('新演示客户')
  await page.getByLabel('联系电话').fill('13800000009')
  await page.getByRole('button', { name: '注册', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('注册成功')
  await page.getByRole('link', { name: '返回客户登录' }).click()
  await expect(page.getByRole('heading', { name: '客户登录', exact: true })).toBeVisible()
  await page.getByLabel('用户名', { exact: true }).fill('new_customer')
  await page.getByLabel('密码', { exact: true }).fill('NewPassword1')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await page.getByRole('link', { name: '我的', exact: true }).click()
  await expect(page.getByRole('heading', { name: '新演示客户' })).toBeVisible()
  await page.getByRole('button', { name: '地址簿 →', exact: true }).click()
  await page.getByRole('button', { name: '新增地址', exact: true }).click()
  await page.getByLabel('联系人', { exact: true }).fill('演示联系人')
  await page.getByLabel('联系电话').fill('13800000009')
  await page.getByLabel('详细地址').fill('仅用于测试的虚构地址')
  await expect(page.getByLabel('经度（可空）')).toHaveCount(0)
  await page.getByRole('button', { name: '保存地址', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('地址已保存')
  await expect(page.locator('article')).toContainText('默认')
  await page.getByRole('button', { name: '编辑', exact: true }).click()
  await page.getByLabel('详细地址').fill('修改后的虚构地址')
  await page.getByRole('button', { name: '保存地址', exact: true }).click()
  await expect(page.locator('article')).toContainText('修改后的虚构地址')
  page.on('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: '删除', exact: true }).click()
  await expect(page.getByText('还没有地址，请先添加。')).toBeVisible()
})

async function login(page: Page, role: 'customer' | 'worker' | 'admin', username = role as string) {
  await page.goto(`/${role}/login`)
  await page.getByLabel('用户名', { exact: true }).fill(username)
  await page.getByLabel('密码', { exact: true }).fill('Demo12345')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page).not.toHaveURL(/login/)
}
test('客户创建标准预约，人员履约，客户确认并评价', async ({ page, context }) => {
  const errors: string[] = []
  page.on('pageerror', (e) => errors.push(e.message))
  await login(page, 'customer')
  await expect(page.getByRole('heading', { name: '首页', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/customer-catalog.png', fullPage: true })
  await page.getByRole('button', { name: /^清洁服务/ }).click()
  await page.getByRole('button', { name: /^日常清洁/ }).click()
  await page.getByRole('button', { name: /^2 小时套餐/ }).click()
  await page.getByRole('button', { name: /^标准预约/ }).click()
  await page.getByRole('button', { name: '提交预约并去支付' }).click()
  await expect(page).toHaveURL(/customer\/pay\/\d+/)
  const orderId = page.url().split('/').at(-1)!
  await page.getByRole('button', { name: '确认模拟支付' }).click()
  await expect(page).toHaveURL(/customer\/result\//)
  await page.getByRole('link', { name: '查看订单进度' }).click()
  await expect(page.getByText('派单成功，人员已安排。', { exact: true })).toBeVisible()
  const codeText = await page.getByText(/服务开始码：/).innerText()
  const code = codeText.match(/\d{6}/)![0]
  const worker = await context.newPage()
  worker.on('pageerror', (e) => errors.push(e.message))
  await login(worker, 'worker')
  await worker.goto(`/worker/orders/${orderId}`)
  await expect(worker.getByText(/服务开始码：/)).toHaveCount(0)
  await worker.getByRole('button', { name: '确认出发' }).click()
  await worker.getByRole('button', { name: '确认到达' }).click()
  await worker.getByLabel('向客户索取服务开始码').fill('000000')
  await worker.getByRole('button', { name: '校验并开始服务' }).click()
  await expect(worker.locator('.error-toast')).toContainText('服务开始码不正确')
  await worker.evaluate(async (id) => {
    const path = '/src/mock/transport.ts',
      module = await import(path)
    const db = module.readDatabase(),
      order = db.orders.find((s: { order: { id: string } }) => s.order.id === id).order
    await module.advanceClock(Math.ceil((Date.parse(order.startTime) - module.mockNow()) / 60000))
  }, orderId)
  await worker.getByLabel('向客户索取服务开始码').fill(code)
  await worker.getByRole('button', { name: '校验并开始服务' }).click()
  await worker.getByRole('button', { name: '提交服务完成' }).click()
  await expect(worker.getByText('待客户确认', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '重新查询最新状态' }).click()
  await page.getByRole('button', { name: '确认完成', exact: true }).click()
  await page.getByLabel('准时', { exact: true }).check()
  await page.getByLabel('评价内容').fill('服务完成，演示闭环通过')
  await page.getByRole('button', { name: '提交评价' }).click()
  await expect(page.getByText(/评价：5 分/)).toContainText('服务完成，演示闭环通过')
  expect(errors).toEqual([])
})

test('分页、筛选、移动视口、后台目录编辑和异常取消', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (e) => errors.push(e.message))
  await login(page, 'admin')
  await expect(page.locator('tbody tr')).toHaveCount(20)
  await page.getByRole('button', { name: '下一页', exact: true }).click()
  await expect(page.locator('tbody tr')).toHaveCount(7)
  await page.getByLabel('订单号 / 服务').fill('no-match')
  await page.getByRole('button', { name: '筛选 / 刷新' }).click()
  await expect(page.getByText('暂无符合条件的订单。')).toBeVisible()
  await page.getByRole('link', { name: '服务规格与价格', exact: true }).click()
  await page
    .locator('tbody tr')
    .filter({ hasText: '日常清洁 2 小时' })
    .getByRole('button', { name: '编辑', exact: true })
    .click()
  await page.getByLabel('标准价（两位小数）').fill('170.00')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.locator('tbody tr').filter({ hasText: '日常清洁 2 小时' })).toContainText(
    '170.00',
  )
  await page.goto('/admin/orders/10002')
  await page.getByLabel('异常取消原因（必填）').fill('管理员演示异常取消')
  await page.getByRole('button', { name: '异常取消并退款' }).click()
  await expect(page.getByText('已全额退款', { exact: true })).toBeVisible()
  await expect(page.getByText('FULL_REFUND_', { exact: false })).toBeVisible()
  await page.getByRole('link', { name: '支付与退款', exact: true }).click()
  await page.getByLabel('订单 ID').fill('10002')
  await page.getByRole('button', { name: '查询', exact: true }).click()
  await expect(page.locator('tbody tr')).toHaveCount(2)
  await page.screenshot({ path: 'test-results/admin-payments.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(
    true,
  )
  expect(errors).toEqual([])
})

test('排班保存与请假、网络异常反馈、路由守卫', async ({ page }) => {
  await page.goto('/worker/schedule')
  await expect(page).toHaveURL(/worker\/login/)
  await login(page, 'worker')
  await page.goto('/worker/schedule')
  await page.getByRole('button', { name: '保存排班', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('排班已保存')
  await page.getByRole('button', { name: '请假', exact: true }).click()
  await page.getByLabel('原因', { exact: true }).fill('演示临时请假')
  await page.getByRole('button', { name: '提交请假', exact: true }).click()
  await page.getByRole('button', { name: '请假记录 →' }).click()
  await expect(page.locator('article')).toContainText('演示临时请假')
  await page.getByRole('button', { name: '撤销请假' }).click()
  await expect(page.locator('article')).toContainText('已取消')
  await page.screenshot({ path: 'test-results/worker-schedule.png', fullPage: true })
  await page.getByRole('dialog').getByRole('button', { name: '关闭' }).click()
  await page.getByRole('button', { name: '修改工作时间' }).click()
  await page.evaluate(async () => {
    const path = '/src/mock/transport.ts'
    ;(await import(path)).simulateNetworkFailure()
  })
  await page.getByRole('button', { name: '保存排班', exact: true }).click()
  await expect(page.locator('.error-toast')).toContainText('网络中断')
  await page.getByRole('button', { name: '保存排班', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('排班已保存')
})
